<wsdl:definitions
     name="dbRefDeletePais"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ServiceBusApplication/SBProjectTPFinal/dbRefDeletePais"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ServiceBusApplication/SBProjectTPFinal/dbRefDeletePais"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/dbRefDeletePais"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="dbRefDeletePais_plt" >
    <plt:role name="dbRefDeletePais_role" >
      <plt:portType name="tns:dbRefDeletePais_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/dbRefDeletePais" schemaLocation="dbRefDeletePais.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="dbRefDeletePaisInput_msg">
        <wsdl:part name="dbRefDeletePaisInput_msg" element="db:dbRefDeletePaisInput"/>
    </wsdl:message>
    <wsdl:portType name="dbRefDeletePais_ptt">
        <wsdl:operation name="dbRefDeletePais">
            <wsdl:input message="tns:dbRefDeletePaisInput_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
